// Code generated by Slice Machine. DO NOT EDIT.

import BentoGrid from './BentoGrid/index.svelte';
import Hero from './Hero/index.svelte';
import Marquee from './Marquee/index.svelte';
import NavigationItem from './NavigationItem/index.svelte';

export const components = {
	bento_grid: BentoGrid,
	hero: Hero,
	marquee: Marquee,
	navigation_item: NavigationItem
};
