// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BruksomraderDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Bruksområder documents
 */
interface BruksomraderDocumentData {
	/**
	 * Slice Zone field in *Bruksområder*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bruksomrader.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BruksomraderDocumentDataSlicesSlice> /**
	 * Meta Title field in *Bruksområder*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: bruksomrader.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Bruksområder*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: bruksomrader.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Bruksområder*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bruksomrader.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Bruksområder document from Prismic
 *
 * - **API ID**: `bruksomrader`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BruksomraderDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BruksomraderDocumentData>,
	'bruksomrader',
	Lang
>;

type ForsideDocumentDataSlicesSlice = MarqueeSlice | HeroSlice;

/**
 * Content for Forside documents
 */
interface ForsideDocumentData {
	/**
	 * Navbar theme field in *Forside*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: dark
	 * - **API ID Path**: forside.navbar_theme
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	navbar_theme: prismic.SelectField<'dark' | 'light', 'filled'>;

	/**
	 * Slice Zone field in *Forside*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: forside.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ForsideDocumentDataSlicesSlice> /**
	 * Meta Title field in *Forside*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: forside.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Forside*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: forside.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Forside*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: forside.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Forside document from Prismic
 *
 * - **API ID**: `forside`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ForsideDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<ForsideDocumentData>,
	'forside',
	Lang
>;

type SettingsDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * CTA Link field in *Settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.cta_link
	 * - **Tab**: Navigation
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * CTA Secondary Link field in *Settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.cta_secondary_link
	 * - **Tab**: Navigation
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_secondary_link: prismic.LinkField;

	/**
	 * Slice Zone field in *Settings*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices[]
	 * - **Tab**: Navigation
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

export type AllDocumentTypes = BruksomraderDocument | ForsideDocument | SettingsDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Subheading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;

	/**
	 * Alignment field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: left
	 * - **API ID Path**: hero.default.primary.alignment
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	alignment: prismic.SelectField<'left' | 'center' | 'right', 'filled'>;

	/**
	 * Theme field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: dark
	 * - **API ID Path**: hero.default.primary.theme
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	theme: prismic.SelectField<'dark' | 'light', 'filled'>;

	/**
	 * Background field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.background
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background: prismic.ImageField<never>;

	/**
	 * Overlay field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.overlay
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	overlay: prismic.BooleanField;

	/**
	 * CTA Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * CTA Secondary Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.cta_secondary_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_secondary_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Hero → With video → Primary*
 */
export interface HeroSliceWithVideoPrimary {
	/**
	 * Heading field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withVideo.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Subheading field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withVideo.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;

	/**
	 * Alignment field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: left
	 * - **API ID Path**: hero.withVideo.primary.alignment
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	alignment: prismic.SelectField<'left' | 'center' | 'right', 'filled'>;

	/**
	 * Theme field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: dark
	 * - **API ID Path**: hero.withVideo.primary.theme
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	theme: prismic.SelectField<'dark' | 'light', 'filled'>;

	/**
	 * Video background field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withVideo.primary.video_background
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	video_background: prismic.LinkToMediaField;

	/**
	 * Overlay field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.withVideo.primary.overlay
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	overlay: prismic.BooleanField;

	/**
	 * CTA Link field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withVideo.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * CTA Secondary Link field in *Hero → With video → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.withVideo.primary.cta_secondary_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_secondary_link: prismic.LinkField;
}

/**
 * With video variation for Hero Slice
 *
 * - **API ID**: `withVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithVideo = prismic.SharedSliceVariation<
	'withVideo',
	Simplify<HeroSliceWithVideoPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithVideo;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *Marquee → Default → Primary → Items*
 */
export interface MarqueeSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Marquee → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Marquee → Default → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
	/**
	 * Heading field in *Marquee → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Items field in *Marquee → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<MarqueeSliceDefaultPrimaryItemsItem>>;

	/**
	 * Speed field in *Marquee → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee.default.primary.speed
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	speed: prismic.NumberField;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MarqueeSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSlice = prismic.SharedSlice<'marquee', MarqueeSliceVariation>;

/**
 * Item in *NavigationItem → With dropdown → Primary → Sub Menu*
 */
export interface NavigationItemSliceWithDropdownPrimaryItemsItem {
	/**
	 * Link field in *NavigationItem → With dropdown → Primary → Sub Menu*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_item.withDropdown.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * icon field in *NavigationItem → With dropdown → Primary → Sub Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_item.withDropdown.primary.items[].icon
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	icon: prismic.KeyTextField;
}

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
	/**
	 * Link field in *NavigationItem → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_item.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NavigationItemSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *NavigationItem → With dropdown → Primary*
 */
export interface NavigationItemSliceWithDropdownPrimary {
	/**
	 * Link field in *NavigationItem → With dropdown → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_item.withDropdown.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Description field in *NavigationItem → With dropdown → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_item.withDropdown.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Sub Menu field in *NavigationItem → With dropdown → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_item.withDropdown.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<NavigationItemSliceWithDropdownPrimaryItemsItem>>;
}

/**
 * With dropdown variation for NavigationItem Slice
 *
 * - **API ID**: `withDropdown`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceWithDropdown = prismic.SharedSliceVariation<
	'withDropdown',
	Simplify<NavigationItemSliceWithDropdownPrimary>,
	never
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault | NavigationItemSliceWithDropdown;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
	'navigation_item',
	NavigationItemSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BruksomraderDocument,
			BruksomraderDocumentData,
			BruksomraderDocumentDataSlicesSlice,
			ForsideDocument,
			ForsideDocumentData,
			ForsideDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSlicesSlice,
			AllDocumentTypes,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceWithVideoPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceWithVideo,
			MarqueeSlice,
			MarqueeSliceDefaultPrimaryItemsItem,
			MarqueeSliceDefaultPrimary,
			MarqueeSliceVariation,
			MarqueeSliceDefault,
			NavigationItemSlice,
			NavigationItemSliceDefaultPrimary,
			NavigationItemSliceWithDropdownPrimaryItemsItem,
			NavigationItemSliceWithDropdownPrimary,
			NavigationItemSliceVariation,
			NavigationItemSliceDefault,
			NavigationItemSliceWithDropdown
		};
	}
}
